
**Data-acquisition-through-Api**

**Summary:**
This project involved collecting data from a website and processing it to get a clearer picture of it. 
Data Acquisition is composed of two words: Data and Acquisition, where data is the raw facts and figures, which could be structured and unstructured and acquisition means acquiring data for the given task at hand.
Preparing (cleaning and arranging) raw data in order to make it appropriate for creating and training models is known as data pre-processing. I have standardized the raw data to make it appropriate for models under Data Pre-processing, and I have removed the unnecessary columns.In addition, I have used data manipulation to find the 5 most expensive properties.
Additionally, I used mongo db to turn my data into a database. To do this, I first read the data into a csv file, connected to the database, then added the database's data name and collection name. To sum up, I was able to successfully gather the data from the website, process it, and connect it to the database.

In [1]:
import requests
import json
import pandas as pd

In [2]:
url='https://api.myhome.ie/search'

In [3]:
data='{"ApiKey":"5f4bc74f-8d9a-41cb-ab85-a1b7cfc86622","CorrelationId":"a8fa2f21-994c-418b-852f-0c14260f93d4","RequestTypeId":2,"RequestVerb":"POST","Endpoint":"https://api.myhome.ie/search","Page":%i,"PageSize":20,"SortColumn":2,"SortDirection":2,"SearchRequest":{"IsBackendSearch":false,"SkipSearchIndex":false,"IsGroupPrivateSearch":false,"IsSaleAgreed":false,"IsSold":false,"IsAuction":false,"IsBoundsSearch":false,"UseFreeTextSearchForKeywords":false,"SearchContent":false,"PropertyIds":[],"GroupIds":[],"ChannelIds":[1],"PropertyTypeIds":[97],"PropertyClassIds":[1],"PropertyStatusIds":[2,12],"SaleTypeIds":[],"FeatureTypeIds":[],"RegionId":2168,"LocalityIds":[],"LocalityNames":[],"NegotiatorIds":[],"SolicitorIds":[],"BuyerSolicitorIds":[],"VendorSolicitorIds":[],"TransferedByUserIds":[],"RowStatusIds":[2],"EnergyRatings":[],"Polygons":[],"Destinations":[],"Tags":[],"PrivateTags":[],"PreSixtyThree":false,"IsActive":true,"HasPhotos":false,"PriceFrequency":"Monthly"}}'

In [4]:
headers={'accept': 'application/json, text/plain, */*',
'accept-encoding': 'gzip, deflate, br',
'accept-language': 'en-US,en-IN;q=0.9,en;q=0.8',
'content-length': '971',
'content-type': 'application/json',
'origin': 'https://www.myhome.ie',
'referer': 'https://www.myhome.ie/',
'sec-ch-ua': '"Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"',
'sec-ch-ua-mobile': '?1',
'sec-ch-ua-platform': '"Android"',
'sec-fetch-dest': 'empty',
'sec-fetch-mode': 'cors',
'sec-fetch-site': 'same-site',
'user-agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36;'}

In [5]:
r=requests.post(url,data=data,headers=headers)
r

In [6]:
r.content
1

1

In [7]:
#create a formatted string of the Python JSON object
def jprint(obj):
    text = json.dumps(obj, sort_keys=True, indent=4)
    print(text)

In [8]:
rdata=json.loads(r.content)

In [9]:
SearchResults=rdata['SearchResults']
len(SearchResults)

20

In [10]:
# Range of search resultcount 
l=[]
for i in range(0,rdata['ResultCount'],20):
    SearchResults=json.loads(requests.post(url,data=(data%i),headers=headers).content)['SearchResults']
    l=l+SearchResults

In [11]:
len(l)

520

Preparing (cleaning and arranging) raw data in order to make it appropriate for creating and training models is known as data pre-processing. I have standardized the raw data to make it appropriate for models under Data Pre-processing, and I have removed the unnecessary columns.

In [12]:
#data normalization 
df=pd.json_normalize(l)
df.head()

,PropertyId,GroupId,RefreshedOn,Address,GroupPhoneNumber,GroupEmail,GroupName,GroupAddress,GroupUrlSlugIdentifier,CreatedOnDate,...,BrochureMap.longitude,BrochureMap.latitude,LatestPriceChangeString,SizeStringFeet,NewHomeSizeString,CustomData.AssociatedArticleUrl,JointAgentGroupName,JointAgentGroupAddress,JointAgentGroupUrl,CustomData.JointAgentGroupId
0,4591798,6406,2022-12-18T13:12:25.8670000+00:00,"Karroc, 14 Myra Manor",,NOEL@KELLY.IE,Noel Kelly Auctioneers Ltd,"Unit 5, Portmarnock Shopping Arcade, Portmarno...",noel-kelly,2022-05-09T09:58:37.7570000+01:00,...,-6.173666,53.432671,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4663987,343393,2022-12-18T12:09:17.5800000+00:00,48 Marian Road,,dundrum@lisneysir.com,Lisney Sotheby's International Realty Dundrum,"11 Main Street, Dundrum, Dublin 14",lisney-dundrum,2022-11-28T21:28:54.5170000+00:00,...,-6.297795,53.292927,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4635791,287268,2022-12-18T11:51:20.9270000+00:00,"28 Priory Drive, Eden Gate",,info@ogormanproperties.com,O'Gorman Properties,"Church Road, Greystones, Co. Wicklow",ogorman-properties,2022-08-24T11:44:55.3670000+01:00,...,-6.079766,53.125252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4650591,358063,2022-12-18T11:33:25.7130000+00:00,"38 Braemor Avenue, Churchtown",,info@beirnewise.ie,Beirne & Wise (Churchtown),"Fields Corner, Churchtown Road Upper, Dublin 14",beirne-wise-churchtown,2022-10-13T13:47:39.7170000+01:00,...,-6.263126,53.301502,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4650005,256413,2022-12-18T11:33:16.3870000+00:00,"17 Riverchapel Square, Riverchapel Wood",,gorey@kinsellaestates.ie,Kinsella Estates,"St. Michaels Road, Gorey, Co. Wexford",kinsella-estates,2022-10-11T16:45:28.3330000+01:00,...,-6.239914,52.638390,"-€6,000 on 8th Nov 22",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df.dtypes

PropertyId                           int64
GroupId                              int64
RefreshedOn                         object
Address                             object
GroupPhoneNumber                    object
                                    ...
CustomData.AssociatedArticleUrl     object
JointAgentGroupName                 object
JointAgentGroupAddress              object
JointAgentGroupUrl                  object
CustomData.JointAgentGroupId       float64
Length: 84, dtype: object

# Dropping unwanted columns from dataframe

In [14]:
df=pd.json_normalize(l)
df.drop(['LatestPriceChangeString','SizeStringFeet','CustomData.AssociatedArticleUrl','NewHomeSizeString','JointAgentGroupName','JointAgentGroupAddress','JointAgentGroupUrl','CustomData.JointAgentGroupId', 'GroupPhoneNumber','Negotiator.ImageUrl','Negotiator.JobTitle', 'CustomData.PromotionalSnippet', 'Negotiator.NegotiatorId','Negotiator.Name',   'Negotiator.Phone', 'Negotiator.Email', 'CustomData.DevelopmentLogoBgColour', 'AdditionalLogoUrls',  'RelatedPropertiesTotal',   'CustomData.HidePostCode',  'CustomData.RelatedPropertyIDs','CustomData.IsMyHomePassport', 'TravelTimes', 'AuctionList',  'Location.lat', 'Location.lon', 'BrochureUrl', 'SeoUrl',   'PhotoCount',   'MainPhoto',    'MainPhotoWeb', 'Photos', 'IsNew','IsSaleAgreed','GroupLogoBgColor','GroupLogoUrl','GroupPremiumLogoUrl','GroupPremiumJointLogoUrl','GroupRectangularLogoUrl','JointGroupRectangularLogoUrl','GroupUrl','IsPremiumAd','IsBuildToRent','IsBuildToRentDevelopment','IsPrivateLandlord','IsBrandBooster','GroupUrlSlugIdentifier',  'SaleTypeId','IsFavourite','HasVideos','HasWebP','IsMappedAccurately','IsTopSpot','BedsString','PriceAsString','PriceChangeIsIncrease','DisplayAddress','PropertyClassId','PropertyClass','PropertyClassUrlSlug','BathString','BerRating','EnergyRatingMediaPath','OrderedDisplayAddress','SeoDisplayAddress', 'BrochureMap.longitude','BrochureMap.latitude','SizeStringMeters', 'OpenViewings','VirtualViewings'],axis=1,inplace=True)

In [15]:
df

,PropertyId,GroupId,RefreshedOn,Address,GroupEmail,GroupName,GroupAddress,CreatedOnDate,ActivatedOn,IsActive,id,PropertyStatus,PropertyType,Negotiator.WebSite
0,4591798,6406,2022-12-18T13:12:25.8670000+00:00,"Karroc, 14 Myra Manor",NOEL@KELLY.IE,Noel Kelly Auctioneers Ltd,"Unit 5, Portmarnock Shopping Arcade, Portmarno...",2022-05-09T09:58:37.7570000+01:00,2022-05-09T15:41:37.2570000+01:00,True,4591798,ForSale,Detached House,http://www.kelly.ie
1,4663987,343393,2022-12-18T12:09:17.5800000+00:00,48 Marian Road,dundrum@lisneysir.com,Lisney Sotheby's International Realty Dundrum,"11 Main Street, Dundrum, Dublin 14",2022-11-28T21:28:54.5170000+00:00,2022-11-28T21:29:17.5800000+00:00,True,4663987,ForSale,Semi-Detached House,https://www.lisney.com/about-us/our-team/dundrum
2,4635791,287268,2022-12-18T11:51:20.9270000+00:00,"28 Priory Drive, Eden Gate",info@ogormanproperties.com,O'Gorman Properties,"Church Road, Greystones, Co. Wicklow",2022-08-24T11:44:55.3670000+01:00,2022-08-24T11:55:21.4230000+01:00,True,4635791,ForSale,Semi-Detached House,http://www.ogormanproperties.com
3,4650591,358063,2022-12-18T11:33:25.7130000+00:00,"38 Braemor Avenue, Churchtown",info@beirnewise.ie,Beirne & Wise (Churchtown),"Fields Corner, Churchtown Road Upper, Dublin 14",2022-10-13T13:47:39.7170000+01:00,2022-10-13T13:58:05.3100000+01:00,True,4650591,ForSale,Terraced House,https://www.beirnewise.ie
4,4650005,256413,2022-12-18T11:33:16.3870000+00:00,"17 Riverchapel Square, Riverchapel Wood",gorey@kinsellaestates.ie,Kinsella Estates,"St. Michaels Road, Gorey, Co. Wexford",2022-10-11T16:45:28.3330000+01:00,2022-10-11T16:51:48.7570000+01:00,True,4650005,ForSale,End of Terrace House,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,4527548,6598,2021-09-06T14:48:28.8300000+01:00,"Saint Christopher's, Riverbank, Ringmahon Road",info@barryauctioneers.ie,Barry Auctioneers & Valuers,"77 South Mall, Cork City Centre, Co. Cork",2021-09-06T14:28:25.4670000+01:00,2021-09-06T14:48:28.8300000+01:00,True,4527548,ForSale,Detached House,http://www.barryauctioneers.ie/
516,4527554,387550,2021-09-06T14:41:44.8900000+01:00,"Coorycommane, Coomhola Bridge",info@bowdensestateagents.com,Bowdens Estate Agents,"Summerhill, Market Street, Bantry, Co. Cork",2021-09-06T14:39:49.6530000+01:00,2021-09-06T14:41:44.8900000+01:00,True,4527554,ForSale,Detached House,NaN
517,4527402,259812,2021-09-04T02:26:32.4770000+01:00,"Dun Gaoithe,Sheskinerone,Dungloe,Co Donegal,F9...",property@sfr.ie,Sherry FitzGerald Rainey,"45 Port Road, Letterkenny, Co Donegal",2021-09-04T02:25:16.3800000+01:00,2021-09-04T02:26:32.4770000+01:00,True,4527402,ForSale,Bungalow,NaN
518,4450449,366768,2021-09-03T17:05:44.1230000+01:00,"120 Ashdrive, Westwood, Ballea Road",info@michaelpigott.ie,Michael Pigott Auctioneer & Valuer,"Main Street, Carrigaline, Co. Cork",2020-08-27T12:47:26.6700000+01:00,2021-09-03T17:05:44.1230000+01:00,True,4450449,ForSale,Semi-Detached House,http://www.michaelpigott.ie
519,4527138,312126,2021-09-03T12:21:35.2830000+01:00,Kilconlea Upper,property@woulfe.ie,DNG Declan Woulfe,"Main Street, Abbeyfeale, Co. Limerick",2021-09-03T12:17:05.2900000+01:00,2021-09-03T12:21:35.2830000+01:00,True,4527138,ForSale,Detached House,NaN

In [16]:
df.drop(['id','Negotiator.WebSite'],axis=1,inplace=True)
df

,PropertyId,GroupId,RefreshedOn,Address,GroupEmail,GroupName,GroupAddress,CreatedOnDate,ActivatedOn,IsActive,PropertyStatus,PropertyType
0,4591798,6406,2022-12-18T13:12:25.8670000+00:00,"Karroc, 14 Myra Manor",NOEL@KELLY.IE,Noel Kelly Auctioneers Ltd,"Unit 5, Portmarnock Shopping Arcade, Portmarno...",2022-05-09T09:58:37.7570000+01:00,2022-05-09T15:41:37.2570000+01:00,True,ForSale,Detached House
1,4663987,343393,2022-12-18T12:09:17.5800000+00:00,48 Marian Road,dundrum@lisneysir.com,Lisney Sotheby's International Realty Dundrum,"11 Main Street, Dundrum, Dublin 14",2022-11-28T21:28:54.5170000+00:00,2022-11-28T21:29:17.5800000+00:00,True,ForSale,Semi-Detached House
2,4635791,287268,2022-12-18T11:51:20.9270000+00:00,"28 Priory Drive, Eden Gate",info@ogormanproperties.com,O'Gorman Properties,"Church Road, Greystones, Co. Wicklow",2022-08-24T11:44:55.3670000+01:00,2022-08-24T11:55:21.4230000+01:00,True,ForSale,Semi-Detached House
3,4650591,358063,2022-12-18T11:33:25.7130000+00:00,"38 Braemor Avenue, Churchtown",info@beirnewise.ie,Beirne & Wise (Churchtown),"Fields Corner, Churchtown Road Upper, Dublin 14",2022-10-13T13:47:39.7170000+01:00,2022-10-13T13:58:05.3100000+01:00,True,ForSale,Terraced House
4,4650005,256413,2022-12-18T11:33:16.3870000+00:00,"17 Riverchapel Square, Riverchapel Wood",gorey@kinsellaestates.ie,Kinsella Estates,"St. Michaels Road, Gorey, Co. Wexford",2022-10-11T16:45:28.3330000+01:00,2022-10-11T16:51:48.7570000+01:00,True,ForSale,End of Terrace House
...,...,...,...,...,...,...,...,...,...,...,...,...
515,4527548,6598,2021-09-06T14:48:28.8300000+01:00,"Saint Christopher's, Riverbank, Ringmahon Road",info@barryauctioneers.ie,Barry Auctioneers & Valuers,"77 South Mall, Cork City Centre, Co. Cork",2021-09-06T14:28:25.4670000+01:00,2021-09-06T14:48:28.8300000+01:00,True,ForSale,Detached House
516,4527554,387550,2021-09-06T14:41:44.8900000+01:00,"Coorycommane, Coomhola Bridge",info@bowdensestateagents.com,Bowdens Estate Agents,"Summerhill, Market Street, Bantry, Co. Cork",2021-09-06T14:39:49.6530000+01:00,2021-09-06T14:41:44.8900000+01:00,True,ForSale,Detached House
517,4527402,259812,2021-09-04T02:26:32.4770000+01:00,"Dun Gaoithe,Sheskinerone,Dungloe,Co Donegal,F9...",property@sfr.ie,Sherry FitzGerald Rainey,"45 Port Road, Letterkenny, Co Donegal",2021-09-04T02:25:16.3800000+01:00,2021-09-04T02:26:32.4770000+01:00,True,ForSale,Bungalow
518,4450449,366768,2021-09-03T17:05:44.1230000+01:00,"120 Ashdrive, Westwood, Ballea Road",info@michaelpigott.ie,Michael Pigott Auctioneer & Valuer,"Main Street, Carrigaline, Co. Cork",2020-08-27T12:47:26.6700000+01:00,2021-09-03T17:05:44.1230000+01:00,True,ForSale,Semi-Detached House
519,4527138,312126,2021-09-03T12:21:35.2830000+01:00,Kilconlea Upper,property@woulfe.ie,DNG Declan Woulfe,"Main Street, Abbeyfeale, Co. Limerick",2021-09-03T12:17:05.2900000+01:00,2021-09-03T12:21:35.2830000+01:00,True,ForSale,Detached House

In [17]:
df.dtypes

PropertyId         int64
GroupId            int64
RefreshedOn       object
Address           object
GroupEmail        object
GroupName         object
GroupAddress      object
CreatedOnDate     object
ActivatedOn       object
IsActive            bool
PropertyStatus    object
PropertyType      object
dtype: object

In addition, I have used data manipulation to find the 5 most expensive properties.

In [18]:
#Highest price property?
top5=df.sort_values('PropertyType',ascending=False,inplace=False, axis=0,ignore_index=True)
(top5.head(5))

,PropertyId,GroupId,RefreshedOn,Address,GroupEmail,GroupName,GroupAddress,CreatedOnDate,ActivatedOn,IsActive,PropertyStatus,PropertyType
0,4553929,344399,2022-05-06T16:30:56.1970000+01:00,12 Melville Terrace,info@imove.ie,iMove,"10 Fairview, Dublin 3",2021-12-15T16:21:22.1630000+00:00,2021-12-15T16:28:29.3270000+00:00,True,ForSale,Townhouse
1,4635558,5689,2022-08-23T16:42:47.6770000+01:00,26 Thomas Hand Street,info@sfcumiskykelly.ie,Sherry Fitzgerald Cumisky Kelly,"21 Drogheda Street, Balbriggan, Co. Dublin",2022-08-23T16:26:25.2400000+01:00,2022-08-23T16:42:47.6770000+01:00,True,ForSale,Townhouse
2,4496327,6124,2022-09-15T16:01:15.0970000+01:00,"Lissadell House, 2 Fitzhaven, Ashbourne Avenue",info@rooneys.eu,Rooney Auctioneers,"99 O'Connell Street, Limerick",2021-04-21T10:05:12.4930000+01:00,2022-09-15T16:01:15.0970000+01:00,True,ForSale,Townhouse
3,4616592,7137,2022-09-25T08:51:46.1370000+01:00,"20 Goldsmith's Avenue, Richmond Hill",info@jeremymurphy.ie,Jeremy Murphy & Associates,"50 South Mall, Cork, T12 ND73",2022-07-14T11:36:39.1670000+01:00,2022-07-14T11:43:26.0470000+01:00,True,ForSale,Townhouse
4,4527615,9433,2021-09-06T16:26:04.0000000+01:00,Main Street Headford Co Galway,info@vincentwalshauctioneers.ie,Vincent Walsh Auctioneers,"St George's Square , Headford, Co. Galway",2021-09-06T16:22:35.7870000+01:00,2021-09-06T16:26:04.0000000+01:00,True,ForSale,Townhouse

Additionally, I used mongo db to turn my data into a database. To do this, I first read the data into a csv file, connected to the database, then added the database's data name and collection name. To sum up, I was able to successfully gather the data from the website, process it, and connect it to the database.

In [19]:
#Establish in mongodb 
# importing the library
import pandas as pd
import pymongo
import urllib
from pymongo import MongoClient

In [20]:
# Load csv dataset
df.to_csv('myhome.csv')

In [21]:
data = pd.read_csv('myhome.csv')

In [22]:
#Connect to MongoDB
client = pymongo.MongoClient("mongodb://Divya:"+ urllib.parse.quote_plus("Divya@0209")+"@ac-ftrsqrg-shard-00-00.xe4uins.mongodb.net:27017,ac-ftrsqrg-shard-00-01.xe4uins.mongodb.net:27017,ac-ftrsqrg-shard-00-02.xe4uins.mongodb.net:27017/?ssl=true&replicaSet=atlas-e5bv9c-shard-0&authSource=admin&retryWrites=true&w=majority")
db = client.test

In [23]:
# insert name of database and name of collection
db = client['myhome']
collection = db['myhomecollection']

In [24]:
data.reset_index(inplace=True)

In [25]:
#insert collection
db.collection.insert_many(df.to_dict('records'))